# What is Slicing and how to use it in the context of numpy

In [ ]:
# https://www.youtube.com/watch?v=PbKOrSottRQ
import numpy as np
arr = np.array([1, 5, 9, 85, 100, 250])

# What if we wanted to return 5, 9, 85?
print(arr[1:4])

# Return from 2nd elt to end of array?
print(arr[1:])

# What if wanted to return from the end, backwards?
print(arr[-3:])
print(arr[-3:-1])

# Return slices in steps
print(arr[::2])    # steps of 2




[ 5  9 85]
[  5   9  85 100 250]
[ 85 100 250]
[ 85 100]
[  1   9 100]


## Slicing a 2D Numpy Array

In [ ]:
a2 = np.array(
    [[1,2,3,4,5], 
     [6,7,8,9,10]])  # create 2d numpy array

# get single elt from 2d array
print(a2[0, 4])

# Slice 2d array, first row only
print(a2[0:1, 1:3])

# Slice 2d array, all  rows
print(a2[0:, 1:4])


5
[[2 3]]
[[2 3 4]
 [7 8 9]]


# What is a Counter object and how does it work?

In [5]:
import numpy as np
from collections import Counter

y = np.array([1, 2, 3, 4, 5, 3])
counter = Counter(y)
value = counter.most_common(1)[0][0]    # Most common tuple, and get first element
print(f'Most common value: {value}')

Most common value: 3


# Numpy bincount demo

In [8]:
y = np.array([1, 2, 3, 4, 5, 3, 5, 5])
np.bincount(y)

array([0, 1, 1, 2, 1, 3])

# Numpy argwhere

In [13]:
y = np.array([1, 2, 3, 4, 5, 3, 5, 5])
print(np.argwhere((y > 2) & (y < 5)))
print(np.argwhere((y > 2) & (y < 5)).flatten())

[[2]
 [3]
 [5]]
[2 3 5]
